site_name: AP Computer Science 2026-27
site_url: https://dkessner.github.io/APCS_2026-27

theme:
  name: material
  palette: 
    primary: deep orange
  logo: images/phyllotaxis_orange.png

extra_css:
  - style.css

nav:
  - Home: index.md
  - class/schedule.md
  - Class:
    - class/intro.md
    - class/syllabus.md
    - class/course_expectations.md
    - class/study_advice.md
    - class/resources.md
    - summer/summer_assignment.md
  - Setup:
    - setup/installation_mac.md
    - setup/github.md
    - setup/command_line.md
    - setup/customization_mac.md
  - Assignments:
    - assignments/assignment0.md
    - assignments/assignment1.md
  - about.md

